# ===================================================================
# == Playwright 自动化测试与报告 - 最终版 docker-compose.yml ==
# ===================================================================
# ==         已为您配置好 n8n 失败通知内部 Webhook          ==
# ===================================================================

services:
  # 服务1：Playwright 浏览器服务 (环境提供者)
  playwright:
    image: mcr.microsoft.com/playwright:v1.45.0-jammy
    container_name: playwright-browsers
    ipc: host
    init: true
    networks:
      - dokploy-net

  # 服务2：Playwright 测试执行器 (核心任务执行者)
  tests:
    build: .
    container_name: playwright-runner
    depends_on:
      - playwright
    environment:
      # 连接到独立的浏览器服务
      - PLAYWRIGHT_SERVICE_URL=ws://playwright:4444
    volumes:
      # 将测试报告写入共享卷
      - reports-volume:/app/playwright-report
    # 关键：当 npm test 失败时，通过内部网络调用 n8n 的 webhook
    command: >
      sh -c "npm test || curl -X POST -H 'Content-Type: application/json' -d '{\"status\":\"failed\", \"message\":\"Playwright tests failed.\", \"report_url\":\"http://bmo.pp.ua:8081\"}' http://n8n:5678/webhook/224d6cc9-6ca4-44cc-b154-ddfa8a2be59a"
    networks:
      - dokploy-net

  # 服务3：测试报告网页服务器 (结果展示者)
  reports:
    image: nginx:alpine
    container_name: playwright-reports-server
    depends_on:
      - tests
    ports:
      # 对外暴露 8081 端口以访问报告
      - "8081:80"
    volumes:
      # 以只读方式挂载共享卷中的报告
      - reports-volume:/usr/share/nginx/html:ro
    networks:
      - dokploy-net

# 定义一个命名的共享存储卷
volumes:
  reports-volume:

# 定义要连接的外部网络
networks:
  dokploy-net:
    name: dokploy-network # 这个名字必须与您 n8n compose 文件中的网络名完全一致
    external: true
